### PR TITLE
Extend api capabilities

### PR DESCRIPTION
**Pull request by miaucl**
Extend the existing api capabilities

- locations: add api implementation
- connections: add missing parameters
- stationboard: add missing parameters
- urlli/urlencode: Add "True" flag for correct formatting of lists (ex. via parameter `via[]=foo1&via[]=foo2`)

_No existing functionality should be compromised, only new things have been added._

I will likely extend the home-assistant integration as well as soon as this PR has been merged and a new version got published.

### CODE REVIEW

**Comment by miaucl** [comment]
Have not yet worked with black linter. Should be fine now ;)

**Comment by miaucl** [comment]
@fabaff Would it be possible to have a new version with this PR? I would like to extend the home assistant integration as well, but first I need a proper release of this library. :)

**Comment by miaucl** [comment]
Sorry to ping again :) @fabaff

**Review by fabaff — APPROVED** [review]
Thanks for your work.

**Pull request merged**
